language: cpp

addons:
  apt:
    sources:
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test
    packages:
      - cmake-data
      - cmake

os: linux

matrix:
  include:
  - compiler: gcc
    addons:
      apt:
        packages:
         - g++-4.8
    env: TOOLSET=g++-4.8
  - compiler: gcc
    addons:
      apt:
        packages:
         - g++-4.9
    env: TOOLSET=g++-4.9
  - compiler: gcc
    addons:
      apt:
        packages:
         - g++-5
    env: TOOLSET=g++-5
  - compiler: gcc
    addons:
      apt:
        packages:
         - g++-6
    env: TOOLSET=g++-6
  - compiler: gcc
    addons:
      apt:
        packages:
         - g++-7
    env: TOOLSET=g++-7

  - compiler: clang
    addons:
      apt:
        sources:
        - llvm-toolchain-precise-3.5
        packages:
        - clang-3.5
    env: TOOLSET=clang++-3.5
  - compiler: clang
    addons:
      apt:
        sources:
        - llvm-toolchain-precise-3.6
        packages:
        - clang-3.6
    env: TOOLSET=clang++-3.6
  - compiler: clang
    addons:
      apt:
        sources:
        - llvm-toolchain-precise-3.7
        packages:
        - clang-3.7
    env: TOOLSET=clang++-3.7
  - compiler: clang
    addons:
      apt:
        sources:
        - llvm-toolchain-precise-3.8
        packages:
        - clang-3.8
    env: TOOLSET=clang++-3.8
  - compiler: clang
    addons:
      apt:
        sources:
        - llvm-toolchain-precise-3.9
        packages:
        - clang-3.9
    env: TOOLSET=clang++-3.9
  - compiler: clang
    addons:
      apt:
        sources:
        - llvm-toolchain-precise-4.0
        packages:
        - clang-4.0
    env: TOOLSET=clang++-4.0
  - compiler: clang
    addons:
      apt:
        sources:
        - llvm-toolchain-precise-5.0
        packages:
        - clang-5.0
    env: TOOLSET=clang++-5.0

  - os: osx
    compiler: clang
    env: TOOLSET=clang++

before_script:
- mkdir build
- cd build
- cmake .. -DCMAKE_CXX_COMPILER=$TOOLSET

script:
- make VERBOSE=1
- ./metacheck_gtest
